<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.jvPw12M' shared service.

return $this->privates['.service_locator.jvPw12M'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('frontendUser' => function (): \App\Entity\FrontendUser {
    return ($this->privates['.errored..service_locator.jvPw12M.App\Entity\FrontendUser'] ?? $this->load('getFrontendUserService.php'));
}, 'translator' => function () {
    return ($this->services['translator'] ?? $this->getTranslatorService());
}));
