<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\FrontendUser\DeleteType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Form/Base/BaseAbstractType.php';
include_once $this->targetDirs[3].'/src/Form/Generic/DeleteThingType.php';
include_once $this->targetDirs[3].'/src/Form/FrontendUser/DeleteType.php';

return $this->privates['App\Form\FrontendUser\DeleteType'] = new \App\Form\FrontendUser\DeleteType();
