<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Security\Voter\FrontendUserVoter' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Authorization/Voter/VoterInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Authorization/Voter/Voter.php';
include_once $this->targetDirs[3].'/src/Security/Voter/Base/BaseVoter.php';
include_once $this->targetDirs[3].'/src/Security/Voter/FrontendUserVoter.php';

return $this->privates['App\Security\Voter\FrontendUserVoter'] = new \App\Security\Voter\FrontendUserVoter();
