<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.jvPw12M.App\Entity\FrontendUser' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.jvPw12M": it references class "App\\Entity\\FrontendUser" but no such service exists.');
