<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Security\FrontendUserProvider' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Core/User/UserProviderInterface.php';
include_once $this->targetDirs[3].'/src/Security/FrontendUserProvider.php';

return $this->privates['App\Security\FrontendUserProvider'] = new \App\Security\FrontendUserProvider(($this->services['doctrine'] ?? $this->getDoctrineService()));
