<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventSubscriber\LoginSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/EventSubscriber/LoginSubscriber.php';

return $this->privates['App\EventSubscriber\LoginSubscriber'] = new \App\EventSubscriber\LoginSubscriber(($this->services['doctrine'] ?? $this->getDoctrineService()));
