parameters:
  APP_ENV: '%env(APP_ENV)%'
  APP_SECRET: '%env(APP_SECRET)%'
  DATABASE_URL: '%env(DATABASE_URL)%'
  MAILER_URL: '%env(MAILER_URL)%'
  MAILER_SENDER: '%env(MAILER_SENDER)%'
  ADMIN_PASSWORD: '%env(ADMIN_PASSWORD)%'
  PUBLIC_DIR: "%kernel.root_dir%/../public"