<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AccountController::indexAction' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'App\\Controller\\Administration\\FrontendUserController::createAction' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'App\\Controller\\Administration\\FrontendUserController::deleteAction' => function () {
    return ($this->privates['.service_locator.jvPw12M'] ?? $this->load('get_ServiceLocator_JvPw12MService.php'));
}, 'App\\Controller\\Administration\\FrontendUserController::toggleLoginEnabled' => function () {
    return ($this->privates['.service_locator.jvPw12M'] ?? $this->load('get_ServiceLocator_JvPw12MService.php'));
}, 'App\\Controller\\Administration\\FrontendUserController::updateAction' => function () {
    return ($this->privates['.service_locator.jvPw12M'] ?? $this->load('get_ServiceLocator_JvPw12MService.php'));
}, 'App\\Controller\\Administration\\SettingsController::indexAction' => function () {
    return ($this->privates['.service_locator.LFdLfZW'] ?? $this->load('get_ServiceLocator_LFdLfZWService.php'));
}, 'App\\Controller\\ContactController::indexAction' => function () {
    return ($this->privates['.service_locator.LPpnSeg'] ?? $this->load('get_ServiceLocator_LPpnSegService.php'));
}, 'App\\Controller\\LoginController::indexAction' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\LoginController::recoverAction' => function () {
    return ($this->privates['.service_locator.HDaYt5M'] ?? $this->load('get_ServiceLocator_HDaYt5MService.php'));
}, 'App\\Controller\\LoginController::resetAction' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'App\\Controller\\RegisterController::registerAction' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'App\\Controller\\AccountController:indexAction' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'App\\Controller\\Administration\\FrontendUserController:createAction' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'App\\Controller\\Administration\\FrontendUserController:deleteAction' => function () {
    return ($this->privates['.service_locator.jvPw12M'] ?? $this->load('get_ServiceLocator_JvPw12MService.php'));
}, 'App\\Controller\\Administration\\FrontendUserController:toggleLoginEnabled' => function () {
    return ($this->privates['.service_locator.jvPw12M'] ?? $this->load('get_ServiceLocator_JvPw12MService.php'));
}, 'App\\Controller\\Administration\\FrontendUserController:updateAction' => function () {
    return ($this->privates['.service_locator.jvPw12M'] ?? $this->load('get_ServiceLocator_JvPw12MService.php'));
}, 'App\\Controller\\Administration\\SettingsController:indexAction' => function () {
    return ($this->privates['.service_locator.LFdLfZW'] ?? $this->load('get_ServiceLocator_LFdLfZWService.php'));
}, 'App\\Controller\\ContactController:indexAction' => function () {
    return ($this->privates['.service_locator.LPpnSeg'] ?? $this->load('get_ServiceLocator_LPpnSegService.php'));
}, 'App\\Controller\\LoginController:indexAction' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\LoginController:recoverAction' => function () {
    return ($this->privates['.service_locator.HDaYt5M'] ?? $this->load('get_ServiceLocator_HDaYt5MService.php'));
}, 'App\\Controller\\LoginController:resetAction' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'App\\Controller\\RegisterController:registerAction' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
