<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\EmailService' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/Interfaces/EmailServiceInterface.php';
include_once $this->targetDirs[3].'/src/Service/EmailService.php';

return $this->privates['App\Service\EmailService'] = new \App\Service\EmailService(($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php')), ($this->services['doctrine'] ?? $this->getDoctrineService()), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()), ($this->services['twig'] ?? $this->getTwigService()), $this->getEnv('MAILER_SENDER'));
