<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\RegisterController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/Base/BaseController.php';
include_once $this->targetDirs[3].'/src/Controller/Base/BaseDoctrineController.php';
include_once $this->targetDirs[3].'/src/Controller/Base/BaseFormController.php';
include_once $this->targetDirs[3].'/src/Controller/Base/BaseUserController.php';
include_once $this->targetDirs[3].'/src/Controller/RegisterController.php';

$this->services['App\Controller\RegisterController'] = $instance = new \App\Controller\RegisterController();

$instance->setContainer(($this->privates['.service_locator.uvEpe2T'] ?? $this->load('get_ServiceLocator_UvEpe2TService.php'))->withContext('App\\Controller\\RegisterController', $this));

return $instance;
