<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEuewvU4\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEuewvU4/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEuewvU4.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEuewvU4\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerEuewvU4\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'EuewvU4',
    'container.build_id' => '9e70407a',
    'container.build_time' => 1535907201,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEuewvU4');
