<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nSNatgR' shared service.

return $this->privates['.service_locator.nSNatgR'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AccountController::indexAction' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'App\\Controller\\Administration\\FrontendUserController::createAction' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'App\\Controller\\Administration\\FrontendUserController::deleteAction' => function () {
    return ($this->privates['.service_locator.jvPw12M'] ?? $this->load('get_ServiceLocator_JvPw12MService.php'));
}, 'App\\Controller\\Administration\\FrontendUserController::toggleLoginEnabled' => function () {
    return ($this->privates['.service_locator.jvPw12M'] ?? $this->load('get_ServiceLocator_JvPw12MService.php'));
}, 'App\\Controller\\Administration\\FrontendUserController::updateAction' => function () {
    return ($this->privates['.service_locator.jvPw12M'] ?? $this->load('get_ServiceLocator_JvPw12MService.php'));
}, 'App\\Controller\\Administration\\SettingsController::indexAction' => function () {
    return ($this->privates['.service_locator.LFdLfZW'] ?? $this->load('get_ServiceLocator_LFdLfZWService.php'));
}, 'App\\Controller\\ContactController::indexAction' => function () {
    return ($this->privates['.service_locator.LPpnSeg'] ?? $this->load('get_ServiceLocator_LPpnSegService.php'));
}, 'App\\Controller\\LoginController::indexAction' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\LoginController::recoverAction' => function () {
    return ($this->privates['.service_locator.HDaYt5M'] ?? $this->load('get_ServiceLocator_HDaYt5MService.php'));
}, 'App\\Controller\\LoginController::resetAction' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'App\\Controller\\RegisterController::registerAction' => function () {
    return ($this->privates['.service_locator.HTHCMm7'] ?? $this->load('get_ServiceLocator_HTHCMm7Service.php'));
}, 'App\\Controller\\AccountController:indexAction' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'App\\Controller\\Administration\\FrontendUserController:createAction' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'App\\Controller\\Administration\\FrontendUserController:deleteAction' => function () {
    return ($this->privates['.service_locator.jvPw12M'] ?? $this->load('get_ServiceLocator_JvPw12MService.php'));
}, 'App\\Controller\\Administration\\FrontendUserController:toggleLoginEnabled' => function () {
    return ($this->privates['.service_locator.jvPw12M'] ?? $this->load('get_ServiceLocator_JvPw12MService.php'));
}, 'App\\Controller\\Administration\\FrontendUserController:updateAction' => function () {
    return ($this->privates['.service_locator.jvPw12M'] ?? $this->load('get_ServiceLocator_JvPw12MService.php'));
}, 'App\\Controller\\Administration\\SettingsController:indexAction' => function () {
    return ($this->privates['.service_locator.LFdLfZW'] ?? $this->load('get_ServiceLocator_LFdLfZWService.php'));
}, 'App\\Controller\\ContactController:indexAction' => function () {
    return ($this->privates['.service_locator.LPpnSeg'] ?? $this->load('get_ServiceLocator_LPpnSegService.php'));
}, 'App\\Controller\\LoginController:indexAction' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\LoginController:recoverAction' => function () {
    return ($this->privates['.service_locator.HDaYt5M'] ?? $this->load('get_ServiceLocator_HDaYt5MService.php'));
}, 'App\\Controller\\LoginController:resetAction' => function () {
    return ($this->privates['.service_locator.qjFrezY'] ?? $this->load('get_ServiceLocator_QjFrezYService.php'));
}, 'App\\Controller\\RegisterController:registerAction' => function () {
    return ($this->privates['.service_locator.HTHCMm7'] ?? $this->load('get_ServiceLocator_HTHCMm7Service.php'));
}));
