<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Normalizer\ArrayCollectionNormalizer' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/NormalizerInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/serializer/Normalizer/NormalizerAwareInterface.php';
include_once $this->targetDirs[3].'/src/Normalizer/ArrayCollectionNormalizer.php';

return $this->privates['App\Normalizer\ArrayCollectionNormalizer'] = new \App\Normalizer\ArrayCollectionNormalizer();
